import { readFile, writeFile } from "node:fs/promises";
import { parse } from "acorn";
import { analyze } from "eslint-scope";
import { build, transform } from "esbuild";

// Scope old implicit scratch globals inside factories. Browser globals stay external.
function factory(source, args, returned) {
  const ast = parse(source, { ecmaVersion: 2022, ranges: true });
  const scope = analyze(ast, { ecmaVersion: 2022, sourceType: "script" });
  const locals = [
    ...new Set(
      scope.globalScope.through
        .filter((ref) => ref.isWrite())
        .map((ref) => ref.identifier.name),
    ),
  ].filter(
    (name) =>
      !args
        .split(",")
        .map((s) => s.trim())
        .includes(name),
  );
  return `export default function(${args}) {\nvar ${locals.join(",")};\n${source}\nreturn ${returned};\n}`;
}
async function bundle(entry, format = "iife") {
  return build({
    entryPoints: [entry],
    bundle: true,
    format,
    ...(format === "iife" ? { globalName: "rhyform" } : {}),
    write: false,
    target: ["es2020"],
    legalComments: "inline",
    plugins: [
      {
        name: "legacy-scope",
        setup(builder) {
          builder.onLoad(
            { filter: /(?:vendor\/viewx|src\/legacy)\.js$/ },
            async ({ path }) => ({
              contents: factory(
                await readFile(path, "utf8"),
                path.endsWith("viewx.js")
                  ? ""
                  : "viewX, svgTools, installTimeline",
                path.endsWith("viewx.js") ? "viewX" : "rhyform",
              ),
              loader: "js",
            }),
          );
        },
      },
    ],
  });
}
const baseLicenses = [
  "LICENSE",
  "vendor/VIEWX-LICENSE",
  "node_modules/svgpath/LICENSE",
];
const outputs = [];
for (const [entry, name, format] of [
  ["src/index.js", "rhyform", "iife"],
  ["src/index-3d.js", "rhyform-3d", "iife"],
  ["src/index-3d.js", "rhyform-3d.module", "esm"],
]) {
  const result = await bundle(entry, format);
  const code = result.outputFiles[0].text.replace(/[\t ]+$/gm, "");
  const files = entry.includes("-3d")
    ? [
        ...baseLicenses,
        "node_modules/three/LICENSE",
        "node_modules/earcut/LICENSE",
      ]
    : baseLicenses;
  const licenses = await Promise.all(
    files.map((path) => readFile(path, "utf8")),
  );
  const output = `/*! RhyformJS — MIT. Bundled dependencies: see THIRD_PARTY_NOTICES.md. Generated by npm run build. */\n${licenses.map((text) => `/*! @license\n${text}\n*/`).join("\n")}\n${code}${format === "iife" ? "\nrhyform = rhyform.default;\n" : ""}`;
  if (format === "iife") {
    const minified = await transform(output, {
      minify: true,
      legalComments: "inline",
      target: "es2020",
    });
    outputs.push([name + ".js", output], [name + ".min.js", minified.code]);
  } else outputs.push([name + ".js", output]);
}
for (const [path, contents] of outputs) {
  if (process.argv.includes("--check")) {
    if ((await readFile(path, "utf8")) !== contents)
      throw new Error(
        `${path} is stale. Run npm run build and include the generated bundle.`,
      );
  } else await writeFile(path, contents);
}
console.log(
  `${process.argv.includes("--check") ? "Verified" : "Built"} ${outputs.map(([path, contents]) => `${path} (${Buffer.byteLength(contents)} bytes)`).join(", ")}`,
);
