import { readFile, writeFile } from 'node:fs/promises';
import { parse } from 'acorn';
import { analyze } from 'eslint-scope';
import { build, transform } from 'esbuild';

// Scope old implicit scratch globals inside factories. Browser globals stay external.
function factory(source, args, returned) {
  const ast = parse(source, { ecmaVersion: 2022, ranges: true });
  const scope = analyze(ast, { ecmaVersion: 2022, sourceType: 'script' });
  const locals = [...new Set(scope.globalScope.through.filter(ref => ref.isWrite()).map(ref => ref.identifier.name))].filter(name => !args.split(',').map(s => s.trim()).includes(name));
  return `export default function(${args}) {\nvar ${locals.join(',')};\n${source}\nreturn ${returned};\n}`;
}
const result = await build({
  entryPoints: ['src/index.js'], bundle: true, format: 'iife', globalName: 'rhyform', write: false,
  target: ['es2020'], legalComments: 'inline',
  plugins: [{ name: 'legacy-scope', setup(builder) {
    builder.onLoad({ filter: /(?:vendor\/viewx|src\/legacy)\.js$/ }, async ({ path }) => ({
      contents: factory(await readFile(path, 'utf8'), path.endsWith('viewx.js') ? '' : 'viewX, svgTools, installTimeline', path.endsWith('viewx.js') ? 'viewX' : 'rhyform'), loader: 'js'
    }));
  }}]
});
const code = result.outputFiles[0].text.replace(/[\t ]+$/gm, '');
// The entry exports the API as default; expose the familiar window.rhyform object.
const licenses = await Promise.all(['LICENSE', 'vendor/VIEWX-LICENSE', 'node_modules/svgpath/LICENSE'].map(path => readFile(path, 'utf8')));
const output = `/*! RhyformJS — MIT. Bundled ViewX and svgpath: see THIRD_PARTY_NOTICES.md. Generated by npm run build. */\n${licenses.map(text => `/*! @license\n${text}\n*/`).join('\n')}\n${code}\nrhyform = rhyform.default;\n`;
const minified = await transform(output, { minify: true, legalComments: 'inline', target: 'es2020' });
for (const [path, contents] of [['rhyform.js', output], ['rhyform.min.js', minified.code]]) {
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== contents) throw new Error(`${path} is stale. Run npm run build and include the generated bundle.`);
  } else await writeFile(path, contents);
}
console.log(`${process.argv.includes('--check') ? 'Verified' : 'Built'} rhyform.js (${Buffer.byteLength(output)} bytes), rhyform.min.js (${Buffer.byteLength(minified.code)} bytes)`);
